databases:
  - name: doctorinoapi
    ipAllowList: []
    databaseName: doctorinoapi_production
    user: doctorinoapi_production
    plan: free

services:
  - type: web
    name: doctorinoapi
    plan: free
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    plan: free